name: Publish to IPNS
description: Publish an IPFS CID to IPNS
branding:
  icon: upload-cloud
  color: green
inputs:
  cid:
    description: CID to publish
    required: true
  host:
    description: IPFS hostname
    default: ipfs.io
  port:
    description: IPFS port
    default: 443
outputs:
  name:
    description: IPNS name
runs:
  using: node16
  main: index.js
