name: Publish to IPNS
description: Publish an IPFS CID to IPNS
branding:
  icon: upload-cloud
  color: green
inputs:
  auth:
    description: IPFS authentication
    required: false
  cid:
    description: CID to publish
    required: true
  host:
    description: IPFS hostname
    required: false
    default: ipfs.epiphyte.cloud
  port:
    description: IPFS port
    required: false
    default: "443"
  protocol:
    description: IPFS protocol
    required: false
    default: https
outputs:
  name:
    description: IPNS name
runs:
  using: node16
  main: index.js
